[package]
name = "special"
version = "0.8.1"
license = "Apache-2.0/MIT"
authors = [
    "Abhishek Chanda <abhishek.becs@gmail.com>",
    "Albert Pang <albert.pang@me.com>",
    "Baxter Eaves <baxyjr@gmail.com>",
    "Ivan Ukhov <ivan.ukhov@gmail.com>",
    "Rúnar Berg Baugsson Sigríðarson <runarberg@zoho.com>",
    "zolkko <zolkko@gmail.com>",
]
description = "The package provides special functions."
documentation = "https://docs.rs/special"
homepage = "https://github.com/stainless-steel/special"
repository = "https://github.com/stainless-steel/special"
readme = "README.md"
categories = ["algorithms", "science"]
keywords = ["beta", "error", "gamma"]

[features]
default = ["std", "system_math"]

# Activating feature "system_math" (which is the default) instructs `special` to
# use the system math C library for mathematical operations. Deactivate this
# default feature if no system math C library is available on your compilation
# target (e.g., if you compile to WebAssembly, or if you want test for undefined
# behaviour using `miri`).
system_math = ["libc"]

# Feature "std" is active by default. Deactivate it if you want to compile to a
# `no_std` target (e.g., a microcontroller). You'll likely want to deactivate
# feature "system_math" as well in this case.
std = []

[dependencies]
libc = {version = "0.2", optional = true} 
libm = "0.2.2" # Only used if default feature "libc" is *not* activated.

[dev-dependencies]
assert = "0.7"
random = "0.12"
