[package]
name = "special"
version = "0.11.0"
edition = "2021"
license = "Apache-2.0 OR MIT"
authors = [
    "Abhishek Chanda <abhishek.becs@gmail.com>",
    "Albert Pang <albert.pang@me.com>",
    "Baxter Eaves <baxyjr@gmail.com>",
    "Christian Amsüss <chrysn@fsfe.org>",
    "Ivan Ukhov <ivan.ukhov@gmail.com>",
    "Robert Bamler <robert.bamler@uni-tuebingen.de>",
    "Rúnar Berg Baugsson Sigríðarson <runarberg@zoho.com>",
    "zolkko <zolkko@gmail.com>",
]
description = "The package provides special functions."
documentation = "https://docs.rs/special"
homepage = "https://github.com/stainless-steel/special"
repository = "https://github.com/stainless-steel/special"
readme = "README.md"
categories = ["algorithms", "no-std::no-alloc", "science"]
keywords = ["beta", "error", "gamma"]

[features]
default = ["no_std"]
no_std = []

[dependencies]
lambert_w = { version = "0.5.2", default-features = false, features = ["50bits", "libm"] }
libm = "0.2"

[dev-dependencies]
assert = "0.7"
random = "0.12"
